logging:
  level:
    com.st: debug

spring:
  application.name: spring-security-rest

server.port: 8080
server-api.path.login: login/

# configure a custom URL for the swagger-ui HTML page
#springdoc:
#  swagger-ui.path: /spring-security-rest/index.html
#  api-docs.path: /spring-security-rest/v3/api-docs
